services:
  nextjs-app:
    image: ${USERNAME}/simasjid-frontend:${TAG:-main}
    env_file:
      - ./.env
    container_name: nextjs-app
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs-app
    networks:
      - webnet

networks:
  webnet:
