name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: Hamba-Allah-Team/SIM-frontend
        token: ${{ secrets.GITHUB_TOKEN }}
        path: SIM-frontend

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # - name: Install dependencies and build Next.js
    #   run: |
    #     cd SIM-frontend
    #     npm install
    #     npm run build -- --no-lint

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        IMAGE_BRANCH=${{ github.ref_name }}
        cd SIM-frontend
        docker build \
          --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
          -t ${{ secrets.DOCKER_USERNAME }}/simasjid-frontend:$IMAGE_BRANCH .
        docker push ${{ secrets.DOCKER_USERNAME }}/simasjid-frontend:$IMAGE_BRANCH

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          BRANCH=${{ github.ref_name }}
          IMAGE=${{ secrets.DOCKER_USERNAME }}/simasjid-frontend:$BRANCH

          echo "Login Docker & pull latest image..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull $IMAGE

          echo "Deploying to server..."
          cd /var/www/simasjid.raihanproject.my.id
          git fetch origin
          git checkout $BRANCH
          git pull origin $BRANCH
          export TAG=${BRANCH}
          export USERNAME=${{ secrets.DOCKER_USERNAME }}

          echo "Stopping old container"
          docker compose down

          echo "Running containers..."
          docker compose up -d